name:                fairy-notation
version:             0.1.0.0
github:              "dylan-thinnes/fairy-notation"
license:             BSD3
author:              "Dylan Thinnes"
maintainer:          "dylan.thinnes@protonmail.com"
copyright:           "2020 Dylan Thinnes"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dylan-thinnes/fairy-notation#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- unordered-containers
- containers
- semirings
- gloss
- diagrams
- diagrams-lib
- diagrams-svg
- colour
- parsec

library:
  source-dirs: src

executables:
  glade-notation-gloss:
    main:                GlossMain.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is GlossMain
    dependencies:
    - fairy-notation
  glade-notation-terminal:
    main:                TermMain.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is TermMain
    dependencies:
    - fairy-notation

tests:
  fairy-notation-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fairy-notation
